# Generated by Django 4.2.4 on 2023-08-19 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='upvote',
        ),
        migrations.AddField(
            model_name='pdf',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvoted_pdfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pdf',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_pdfs', to=settings.AUTH_USER_MODEL),
        ),
    ]
