# Generated by Django 4.2.4 on 2023-08-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_pdf_downvote_remove_pdf_upvote_pdf_downvotes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='pdf',
            name='downvote',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdf',
            name='upvote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
