# Generated by Django 4.2.4 on 2023-08-19 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_remove_pdf_downvotes_remove_pdf_upvotes_pdf_downvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='downvotes',
            field=models.ManyToManyField(related_name='downvoted_pdfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pdf',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvoted_pdfs', to=settings.AUTH_USER_MODEL),
        ),
    ]
