# Generated by Django 4.2.4 on 2023-10-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_pdf_downvotes_pdf_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='topic',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
